class FuncionarioBO:
    # FuncionarioDTO is a class object that contains the data of a Funcionario (matricula: int, nome: str, email: str, cargo: Cargo, salario: float)
    FuncionarioDTO = None

    def __init__(self) -> None:
        self.funcionarioDAO = None
        ...
    def inserir(self, funcionarioDTO: FuncionarioDTO)-> None: ...
    def remover(self, matricula: int)-> None: ...
    def listar(self) -> list: ...
    def buscar(self, matricula: int) -> FuncionarioDTO: ...
